grammar test;
impurt: 'import' ':' ':'
        'from' '(' ACCESSTYPE  ((','ACCESSTYPE)+ | (',' '*')) ')'
        '.' ';' ';';
//LIBRARY_NAME: [A-Za-z]+;
LIBRARY_NAME: [A-Z_$][a-zA-Z_$0-9]*;
WHITE_SPACE: [ \n\r\t] -> skip;
ACCESSTYPE: D I R E C T A C C E S S|'indirectAccess'|'restricted';
fragment A:[aA];
fragment B:[bB];
fragment C:[cC];
fragment D:[dD];
fragment E:[eE];
fragment F:[fF];
fragment G:[gG];
fragment H:[hH];
fragment I:[iI];
fragment J:[jJ];
fragment K:[kK];
fragment L:[lL];
fragment M:[mM];
fragment N:[nN];
fragment O:[oO];
fragment P:[pP];
fragment Q:[qQ];
fragment R:[rR];
fragment S:[sS];
fragment T:[tT];
fragment U:[uU];
fragment V:[vV];
fragment W:[wW];
fragment X:[xX];
fragment Y:[yY];
fragment Z:[zZ];